#!/usr/bin/env node
const { spawn } = require('child_process');

try {
    const v = spawn('v', ['lint'], {
        encoding: 'utf8',
        env: Object.assign({ FORCE_COLOR: true }, process.env),
    });

    v.stdout.on('data', (data) => {
        process.stdout.write(data);
    });

    v.stderr.on('data', (data) => {
        process.stdout.write(data);
    });

    v.on('error', (err) => {
        process.stdout.write(err);
        process.exit(1);
    });

    v.on('exit', (code) => {
        if (code === 0) {
            process.exit(0);
        } else {
            process.exit(code);
        }
    });
} catch (e) {
    console.log(e);
}
